### ISSUE TITLE
Mock for Combine

### ISSUE THREAD

**Issue by keithcml** [uber/mockolo#175]
I have tried to annotate with the following for my AnyPublisher

```swift
/// @mockable(combine: publisher = CurrentValueSubject)
```
But the generator produces PassthroughSubject as

```swift
public private(set) var publisherSubject: PassthroughSubject...
```

I would expect there is a CurrentValueSubject instead.

**Comment by ffittschen** [comment]
We are currently facing the same issue. After investigating it a bit, it only fails to generate the mock as a `CurrentValueSubject`, if it can't find any default value. E.g. in the following example, mockolo will generate a `fooPublisherSubject = PassthroughSubject<FooEnum, Never>()` and a `barSubject = CurrentValueSubject<Bool, Never>(false)`

```swift
public enum FooEnum {
    case one, two, three
}

/// @mockable(combine: fooPublisher = CurrentValueSubject; barPublisher = CurrentValueSubject)
public protocol SomeStream: AnyObject {
    var fooPublisher: AnyPublisher<FooEnum, Never> { get }
    var barPublisher: AnyPublisher<Bool, Never> { get }
}
```

In [these lines of code](https://github.com/uber/mockolo/blob/master/Sources/MockoloFramework/Templates/VariableTemplate.swift#L154-L158), mockolo will decide to fall back to a `PassthroughSubject` in case it can't find a default value.

As mockolo is already capable of adding parameters to the `init` method in the case of assigning an AnyPublisher to a property, we might be able to extend it to add parameters for types of the CurrentValueSubjects as well?

**Comment by maxwellE** [comment]
I believe this was fixed in #186 ?

**Comment by uhooi** [comment]
@keithcml Can you confirm that it is fixed?

**Comment by kernandreas** [comment]
Just ran in the same situation. Thank you @ffittschen for the investigation. How did you work around in your code base?

Btw. #186 does not fix the root cause. It adds a new flag to disable Subject synthesis for all AnyPublisher properties.

**Comment by fummicc1** [comment]
I try to fix this issue by adding a new metadata to set a default value of CurrentValueSubject  in https://github.com/uber/mockolo/pull/234.

If you have any advice, please let me know.

**Comment by fummicc1** [comment]
After reviewing my idea, I believe we can resolve this issue by using the `--disable-combine-default-values` option. Therefore, I'll be closing this PR. Please feel free to reopen it whenever you wish to continue discussing this topic.
