### ISSUE TITLE
support for async properties?

### ISSUE THREAD

**Issue by alessioborraccino** [uber/mockolo#210]
After swift 5.6 it's possible to declare in protocols async and/or throws properties:

```
/// @mockable
protocol AsyncProperties {
  var isAvailable: Bool { get async throws }
}
```

but mockolo still doesnt support this syntax, and generates just a simple `Bool` property. 

```
class AsyncPropertiesMock: AsyncProperties {
    init() { }
    init(isAvailable: Bool = false) {
        self.isAvailable = isAvailable
    }


    var isAvailableSetCallCount = 0
    var isAvailable: Bool = false { didSet { isAvailableSetCallCount += 1 } }
}
```

is there any plan to update it so that `/// @mockable` can successfully also generate an `async throws` handler for this case?

**Comment by sidepelican** [comment]
It should be fixed, but I think it is a less common requirement, so it is not a priority.

**Comment by alessioborraccino** [comment]
Not fixed, without a handler i cant test any throwing because the mock doesnt actually throws. Hoping in an update eventually :)

**Comment by sidepelican** [comment]
shipped in 2.2.0
